### ISSUE TITLE
colors are off in terminal

### ISSUE THREAD

**Issue by kernel-io** [rose-pine/zed#13]
just updated to this plugin versus what used to come with zed and the colours are all whack in the terminal. i.e: the whites and the pure blacks, the whites make things unreadable.

<img width="679" alt="image" src="https://github.com/user-attachments/assets/32835c3f-bbab-4bf9-a4ec-d703d7259708">

**Comment by ThatOneCalculator** [comment]
Please wait for v1.1.2 to be merged, this issue has been fixed but the zed team hasn't merged it yet.

**Comment by ThatOneCalculator** [comment]
In the meantime, you can copy `themes/*` from this repo to your zed config folder in the `themes` dir.
