### ISSUE TITLE
Rosé Pine Theme looks like buggy version of Dawn?

### ISSUE THREAD

**Issue by OfficialCRUGG** [rose-pine/zed#2]
Rosé Pine Dawn and Moon work, but Rosé Pine looks like a buggy version of Dawn.

This is Dawn:
![image](https://github.com/rose-pine/zed/assets/25248999/a0519bc6-408e-4a13-a25a-b23de2916223)

And this is how normal Rosé Pine looks for whatever reason:
![image](https://github.com/rose-pine/zed/assets/25248999/aff23322-776b-47c1-aa6e-a184b8abf1b6)

**Comment by emillinden** [comment]
Downloading and installing the extension manually ("Install Dev Extension" in Zed) seems to fix this issue. Possibly a naming conflict since rose-pine.json and rose-pine-dawn.json share the same "name" value.
