### ISSUE TITLE
Current item selection in suggestions barely distinguishable in dawn theme

### ISSUE THREAD

**Issue by SergoGansta777** [rose-pine/zed#6]
It looks like (second item from top selected):
![CleanShot 2024-07-18 at 20 22 57@2x](https://github.com/user-attachments/assets/b450c954-ea10-41dd-9bf6-e1d5e9f2a6e6)

**Comment by ThatOneCalculator** [comment]
I can't seem to find what theme key this corresponds to :(

**Comment by SergoGansta777** [comment]
I think it's okay now
![CleanShot 2024-08-18 at 02 29 29@2x](https://github.com/user-attachments/assets/8385bd68-cf26-4370-8dd5-931068ffc4de)
